### ISSUE TITLE
English and Tibetan Sun of Faith are no longer

### ISSUE THREAD

**Issue by Quintman** [yale-web-technologies/mirador-project#77]
Tibetan and English text is no longer linked across annotation streams (in Sun of Faith)

**Comment by gigamorph** [comment]
Fixed it.

**Comment by Quintman** [comment]
The links now seem to work inconsistently: sometimes they work sometimes not. Also, links worked from the Tibetan to English (click on Tibetan, it highlights corresponding English) but not the other way around.

**Comment by Quintman** [comment]
Actually, we are still having this problem. For example, when we have 2 annotation windows open (English, Tibetan Sun of Faith) set to "all", clicking on the English no longer links to Tibetan and vice versa.
